# Generated by Django 5.0.6 on 2024-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prix_par_aliment', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Quantite_dans_le_stock', models.IntegerField()),
                ('Quantite_vendus', models.IntegerField()),
                ('Date_du_stock', models.DateField(auto_now_add=True)),
                ('Derniere_date_de_vente', models.DateField(auto_now=True)),
            ],
        ),
    ]
